name: Ping Gallery Salon
on:
  schedule:
    - cron: '0 0 * * 0'  # 매주 일요일 00:00 UTC
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping gallery salon
        run: curl -s https://portfolio-gallery-delta.vercel.app/gallery/salon > /dev/null
