name: Ping Homepage
on:
  schedule:
    - cron: '0 0 * * 3'  # 매주 수요일 00:00 UTC
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping portfolio homepage
        run: curl -s https://portfolio-gallery-delta.vercel.app/ > /dev/null
